version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fp-ts
    versions:
    - 2.10.3
  - dependency-name: vscode-languageserver-protocol
    versions:
    - 3.16.0
